version: "3"
services:
  server:
    image: assaf-challenge
    ports:
      - 3000
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    volumes:
    - ./start.sh:/start.sh
    command: /start.sh

  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server